# Generated by Django 3.1.6 on 2021-02-15 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 44, 9, 236729))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('day', models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AddField(
            model_name='company',
            name='qr_url',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='TrainTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 44, 9, 242748))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('close_timer', models.BooleanField(default=False)),
                ('minutes', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 44, 9, 242748))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('close_timer', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('limit_people', models.IntegerField(default=0)),
                ('days', models.ManyToManyField(blank=True, null=True, to='api.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='api.Service'),
        ),
    ]
