# Generated by Django 3.1.6 on 2021-02-15 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210215_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 20, 8, 31, 121897)),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 20, 8, 31, 127936)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 20, 8, 31, 127936)),
        ),
    ]
