# Generated by Django 3.1.6 on 2021-02-17 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210217_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 17, 34, 28, 156777)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 17, 34, 28, 156777)),
        ),
    ]
