# Generated by Django 3.1.6 on 2021-02-20 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210220_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedtrains',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 14, 51, 20, 439247)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 14, 51, 20, 440244)),
        ),
    ]
