# Generated by Django 3.1.6 on 2021-02-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210220_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinishedTrains',
            new_name='FinishedTrain',
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 14, 54, 34, 547489)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 14, 54, 34, 548485)),
        ),
    ]
