# Generated by Django 3.1.6 on 2021-02-25 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210225_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 20, 29, 7, 582929)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 20, 29, 7, 583928)),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
