# Generated by Django 3.1.6 on 2021-02-27 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210225_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='limit_people',
        ),
        migrations.AddField(
            model_name='schedule',
            name='limit_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 15, 14, 8, 447083)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 27, 15, 14, 8, 447083)),
        ),
    ]
