# Generated by Django 3.1.6 on 2021-03-04 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210227_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('end_time', models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 1))),
                ('limit_people', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='limit_people',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 31, 47, 484656)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 31, 47, 485653)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timelines',
            field=models.ManyToManyField(blank=True, null=True, to='api.TimeLine'),
        ),
    ]
