# Generated by Django 2.2.19 on 2021-03-20 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210319_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonuses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 19, 15, 46, 459702)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 19, 15, 46, 460732)),
        ),
    ]
