# Generated by Django 3.1.7 on 2021-03-29 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210325_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='close_timer',
        ),
        migrations.RemoveField(
            model_name='traintimer',
            name='close_timer',
        ),
        migrations.RemoveField(
            model_name='traintimer',
            name='minutes',
        ),
        migrations.AddField(
            model_name='timer',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 19, 56, 13, 835473)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 19, 56, 13, 835473)),
        ),
    ]
