# Generated by Django 3.1.7 on 2021-03-31 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210329_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='is_expired',
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 14, 19, 37, 660265)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 14, 19, 37, 660265)),
        ),
    ]
