# Generated by Django 3.1.7 on 2021-04-05 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210331_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='all_bonuses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 17, 27, 45, 559889)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 17, 27, 45, 559889)),
        ),
    ]
