# Generated by Django 3.1.7 on 2021-04-06 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210405_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
                ('code', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 54, 40, 434123)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 54, 40, 434123)),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
