# Generated by Django 3.1.7 on 2021-04-06 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210406_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 56, 49, 695729)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 56, 49, 695729)),
        ),
    ]
