# Generated by Django 3.1.7 on 2021-04-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210410_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='month_bonuses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 14, 49, 53, 885127)),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 14, 49, 53, 885127)),
        ),
    ]
